"""empty message

Revision ID: 958573f88946
Revises: 2be5c4dc6132
Create Date: 2019-05-29 17:40:18.783531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958573f88946'
down_revision = '2be5c4dc6132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'message')
    # ### end Alembic commands ###
