"""empty message

Revision ID: 3b6245486dea
Revises: 958573f88946
Create Date: 2019-06-02 16:22:09.040886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6245486dea'
down_revision = '958573f88946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isAdmin')
    # ### end Alembic commands ###
